# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqJT61aI_FI4aYFXAi7OeuRgIQRhDAHj
"""

import pandas as pd
from datetime import datetime

# Corrected API response data
api_response = {
  "agricultural_advisory": {
    "fertilizer_recommendations": [],
    "irrigation_advice": "Insufficient data for irrigation advice",
    "pest_risk_assessment": "High pest risk - monitor crops closely",
    "sustainability_score": 0.5
  },
  "crop_recommendations": {
    "expected_returns": [],
    "suitability_analysis": [],
    "top_recommendations": []
  },
  "location_information": {
    "climate_zone": "Subtropical",
    "coordinates": {
      "latitude": 28.6139,
      "longitude": 77.209
    },
    "elevation_estimate": 772.18,
    "growing_season": {
      "main_season": "April-September",
      "off_season": "October-March"
    },
    "timezone": "auto"
  },
  "market_analysis": {
    "best_performing_crops": [
      [
        "sugarcane",
        {
          "demand": "High",
          "price_per_ton": 2800,
          "trend": "Increasing"
        }
      ],
      [
        "corn",
        {
          "demand": "High",
          "price_per_quintal": 1500,
          "trend": "Increasing"
        }
      ],
      [
        "rice",
        {
          "demand": "High",
          "price_per_quintal": 1800,
          "trend": "Increasing"
        }
      ]
    ],
    "current_prices": {
      "corn": {
        "demand": "High",
        "price_per_quintal": 1500,
        "trend": "Increasing"
      },
      "cotton": {
        "demand": "Low",
        "price_per_quintal": 5800,
        "trend": "Stable"
      },
      "rice": {
        "demand": "High",
        "price_per_quintal": 1800,
        "trend": "Increasing"
      },
      "soybean": {
        "demand": "Medium",
        "price_per_quintal": 3200,
        "trend": "Decreasing"
      },
      "sugarcane": {
        "demand": "High",
        "price_per_ton": 2800,
        "trend": "Increasing"
      },
      "wheat": {
        "demand": "Medium",
        "price_per_quintal": 2100,
        "trend": "Stable"
      }
    },
    "trend_analysis": {
      "corn": "Bullish market - good time to plant",
      "rice": "Bullish market - good time to plant",
      "soybean": "Bearish market - consider alternatives",
      "sugarcane": "Bullish market - good time to plant"
    }
  },
  "metadata": {
    "api_version": "1.0",
    "area_hectares": 1.0,
    "data_sources": [
      "SoilGrids",
      "Open-Meteo",
      "Simulated Market Data"
    ],
    "timestamp": "2025-09-07T16:06:56.807176"
  },
  "ml_training_features": {
    "data_quality_score": 0.6,
    "feature_vector": {
      "current_precipitation": 0.1,
      "current_relative_humidity_2m": 79,
      "current_soil_moisture_0_1cm": 0.4,
      "current_soil_temperature_0cm": 32.4,
      "current_temperature_2m": 30.6,
      "current_wind_speed_10m": 6.3,
      "growing_degree_days": 135.15,
      "water_stress_index": 1
    },
    "target_variables": {}
  },
  "soil_analysis": {
    "health_index": 0.5,
    "interpretation": [],
    "properties": {}
  },
  "weather_analysis": {
    "current_conditions": {
      "precipitation": 0.1,
      "relative_humidity_2m": 79,
      "soil_moisture_0_1cm": 0.4,
      "soil_temperature_0cm": 32.4,
      "temperature_2m": 30.6,
      "wind_speed_10m": 6.3
    },
    "daily_forecast": {
      "precipitation_hours": [
        23.0,
        10.0,
        0.0,
        0.0,
        0.0,
        0.0,
        3.0
      ],
      "precipitation_sum": [
        16.0,
        1.4,
        0.0,
        0.0,
        0.0,
        0.0,
        0.3
      ],
      "temperature_2m_max": [
        32.2,
        31.7,
        33.2,
        33.5,
        32.8,
        33.9,
        32.9
      ],
      "temperature_2m_min": [
        25.9,
        25.1,
        25.8,
        25.7,
        25.4,
        25.8,
        26.4
      ],
      "time": [
        "2025-09-07",
        "2025-09-08",
        "2025-09-09",
        "2025-09-10",
        "2025-09-11",
        "2025-09-12",
        "2025-09-13"
      ],
      "wind_speed_10m_max": [
        8.7,
        9.2,
        7.7,
        12.3,
        11.6,
        9.5,
        8.2
      ]
    },
    "growing_degree_days": 135.15,
    "hourly_forecast": {
      "precipitation": [
        1.8,
        1.2,
        0.9,
        0.3,
        0.7,
        0.5,
        0.7,
        0.4,
        0.7,
        0.8,
        0.1,
        0.1,
        0.2,
        0.2,
        1.2,
        0.3,
        1.7,
        0.7,
        0.6,
        1.3,
        0.8,
        0.0,
        0.5,
        0.3
      ],
      "relative_humidity_2m": [
        92,
        91,
        92,
        92,
        92,
        93,
        93,
        93,
        90,
        87,
        82,
        73,
        71,
        68,
        75,
        77,
        80,
        82,
        85,
        89,
        89,
        91,
        90,
        91
      ],
      "soil_moisture_0_1cm": [
        0.407,
        0.408,
        0.408,
        0.407,
        0.407,
        0.398,
        0.399,
        0.399,
        0.4,
        0.4,
        0.4,
        0.4,
        0.399,
        0.398,
        0.399,
        0.399,
        0.4,
        0.401,
        0.401,
        0.403,
        0.403,
        0.403,
        0.404,
        0.404
      ],
      "soil_temperature_0cm": [
        26.8,
        26.6,
        26.2,
        26.1,
        25.9,
        26.5,
        26.4,
        26.9,
        28.4,
        29.8,
        30.9,
        36.5,
        37.1,
        36.1,
        33.6,
        33.6,
        31.2,
        29.5,
        28.2,
        27.6,
        27.2,
        27.1,
        27.0,
        26.4
      ],
      "temperature_2m": [
        26.9,
        26.6,
        26.2,
        26.1,
        25.9,
        26.4,
        26.3,
        26.4,
        26.9,
        27.7,
        28.8,
        31.4,
        31.9,
        32.2,
        31.1,
        31.0,
        30.2,
        29.4,
        28.5,
        27.8,
        27.4,
        27.2,
        26.9,
        26.5
      ],
      "time": [
        "2025-09-07T00:00",
        "2025-09-07T01:00",
        "2025-09-07T02:00",
        "2025-09-07T03:00",
        "2025-09-07T04:00",
        "2025-09-07T05:00",
        "2025-09-07T06:00",
        "2025-09-07T07:00",
        "2025-09-07T08:00",
        "2025-09-07T09:00",
        "2025-09-07T10:00",
        "2025-09-07T11:00",
        "2025-09-07T12:00",
        "2025-09-07T13:00",
        "2025-09-07T14:00",
        "2025-09-07T15:00",
        "2025-09-07T16:00",
        "2025-09-07T17:00",
        "2025-09-07T18:00",
        "2025-09-07T19:00",
        "2025-09-07T20:00",
        "2025-09-07T21:00",
        "2025-09-07T22:00",
        "2025-09-07T23:00"
      ]
    },
    "water_stress_index": 1
  }
}

def create_agriculture_dataset(api_data):
    """
    Creates structured datasets from agriculture API response

    Parameters:
    api_data (dict): The JSON API response

    Returns:
    dict: A dictionary containing multiple pandas DataFrames
    """

    datasets = {}

    # 1. Location Information Dataset
    location_data = api_data['location_information']
    datasets['location_info'] = pd.DataFrame({
        'latitude': [location_data['coordinates']['latitude']],
        'longitude': [location_data['coordinates']['longitude']],
        'elevation': [location_data['elevation_estimate']],
        'climate_zone': [location_data['climate_zone']],
        'growing_season_main': [location_data['growing_season']['main_season']],
        'growing_season_off': [location_data['growing_season']['off_season']],
        'timezone': [location_data['timezone']]
    })

    # 2. Current Weather Conditions Dataset
    current_weather = api_data['weather_analysis']['current_conditions']
    datasets['current_weather'] = pd.DataFrame({
        'temperature_2m': [current_weather['temperature_2m']],
        'relative_humidity_2m': [current_weather['relative_humidity_2m']],
        'precipitation': [current_weather['precipitation']],
        'wind_speed_10m': [current_weather['wind_speed_10m']],
        'soil_temperature_0cm': [current_weather['soil_temperature_0cm']],
        'soil_moisture_0_1cm': [current_weather['soil_moisture_0_1cm']],
        'water_stress_index': [api_data['weather_analysis']['water_stress_index']],
        'growing_degree_days': [api_data['weather_analysis']['growing_degree_days']],
        'timestamp': [api_data['metadata']['timestamp']]
    })

    # 3. Daily Forecast Dataset
    daily_forecast = api_data['weather_analysis']['daily_forecast']
    datasets['daily_forecast'] = pd.DataFrame({
        'date': daily_forecast['time'],
        'temp_max': daily_forecast['temperature_2m_max'],
        'temp_min': daily_forecast['temperature_2m_min'],
        'precipitation_sum': daily_forecast['precipitation_sum'],
        'precipitation_hours': daily_forecast['precipitation_hours'],
        'wind_speed_max': daily_forecast['wind_speed_10m_max']
    })

    # 4. Hourly Forecast Dataset
    hourly_forecast = api_data['weather_analysis']['hourly_forecast']
    datasets['hourly_forecast'] = pd.DataFrame({
        'timestamp': hourly_forecast['time'],
        'temperature_2m': hourly_forecast['temperature_2m'],
        'relative_humidity_2m': hourly_forecast['relative_humidity_2m'],
        'precipitation': hourly_forecast['precipitation'],
        'soil_temperature_0cm': hourly_forecast['soil_temperature_0cm'],
        'soil_moisture_0_1cm': hourly_forecast['soil_moisture_0_1cm']
    })

    # 5. Market Prices Dataset
    market_prices = api_data['market_analysis']['current_prices']
    market_data = []
    for crop, details in market_prices.items():
        market_data.append({
            'crop': crop,
            'price': details.get('price_per_quintal', details.get('price_per_ton', 0)),
            'price_unit': 'per_quintal' if 'price_per_quintal' in details else 'per_ton',
            'demand': details['demand'],
            'trend': details['trend']
        })
    datasets['market_prices'] = pd.DataFrame(market_data)

    # 6. Best Performing Crops Dataset
    best_crops = api_data['market_analysis']['best_performing_crops']
    best_crops_data = []
    for crop_data in best_crops:
        crop, details = crop_data
        best_crops_data.append({
            'crop': crop,
            'price': details.get('price_per_quintal', details.get('price_per_ton', 0)),
            'price_unit': 'per_quintal' if 'price_per_quintal' in details else 'per_ton',
            'demand': details['demand'],
            'trend': details['trend']
        })
    datasets['best_performing_crops'] = pd.DataFrame(best_crops_data)

    # 7. Market Trend Analysis Dataset
    trend_analysis = api_data['market_analysis']['trend_analysis']
    trend_data = []
    for crop, trend in trend_analysis.items():
        trend_data.append({
            'crop': crop,
            'market_trend': trend
        })
    datasets['market_trends'] = pd.DataFrame(trend_data)

    # 8. Agricultural Advisory Dataset
    advisory = api_data['agricultural_advisory']
    datasets['advisory'] = pd.DataFrame({
        'irrigation_advice': [advisory['irrigation_advice']],
        'pest_risk': [advisory['pest_risk_assessment']],
        'sustainability_score': [advisory['sustainability_score']],
        'timestamp': [api_data['metadata']['timestamp']]
    })

    # 9. ML Features Dataset
    ml_features = api_data['ml_training_features']['feature_vector']
    ml_data = {k: [v] for k, v in ml_features.items()}
    ml_data['data_quality_score'] = [api_data['ml_training_features']['data_quality_score']]
    ml_data['timestamp'] = [api_data['metadata']['timestamp']]
    datasets['ml_features'] = pd.DataFrame(ml_data)

    # 10. Metadata Dataset
    metadata = api_data['metadata']
    datasets['metadata'] = pd.DataFrame({
        'api_version': [metadata['api_version']],
        'area_hectares': [metadata['area_hectares']],
        'data_sources': [', '.join(metadata['data_sources'])],
        'timestamp': [metadata['timestamp']]
    })

    # 11. Soil Analysis Dataset
    soil_data = api_data['soil_analysis']
    datasets['soil_analysis'] = pd.DataFrame({
        'health_index': [soil_data['health_index']],
        'timestamp': [api_data['metadata']['timestamp']]
    })

    return datasets

# Create the datasets from the API response
agriculture_datasets = create_agriculture_dataset(api_response)

# Display information about each dataset
print("Agriculture Data Analysis Datasets:")
print("===================================")
for name, df in agriculture_datasets.items():
    print(f"{name}: {df.shape[0]} rows x {df.shape[1]} columns")

# Example: Access the market prices dataset
print("\nMarket Prices:")
print(agriculture_datasets['market_prices'].head())

# Example: Access the daily forecast
print("\nDaily Forecast:")
print(agriculture_datasets['daily_forecast'].head())

# Save all datasets to CSV files
for name, df in agriculture_datasets.items():
    filename = f"agriculture_{name}.csv"
    df.to_csv(filename, index=False)
    print(f"Saved {filename}")

print("\nAll datasets have been saved to CSV files.")


# Replace 'your_data.csv' with your actual file
df = pd.read_csv("agriculture_current_weather.csv")

df.head()

def get_agri_insights(row):
    temp = row["temperature_2m"]
    humidity = row["relative_humidity_2m"]
    precip = row["precipitation"]
    wind_speed = row["wind_speed_10m"]
    soil_temp = row["soil_temperature_0cm"]
    soil_moisture = row["soil_moisture_0_1cm"]
    wsi = row["water_stress_index"]
    gdd = row["growing_degree_days"]

    insights = {}

    # 1️⃣ Crop Water Requirement (simple heuristic)
    cwr = (0.0023 * (temp + 17.8) * (temp - 5) * (1 + wind_speed/100))
    insights["crop_water_requirement_mm"] = round(max(cwr, 0), 2)

    # 2️⃣ Pest & Disease Risk
    if temp > 28 and humidity > 75:
        risk = "High risk"
    elif humidity > 65 and 22 < temp < 28:
        risk = "Moderate risk"
    else:
        risk = "Low risk"
    insights["pest_disease_risk"] = risk

    # 3️⃣ Optimal Planting Times
    if 20 <= soil_temp <= 30 and soil_moisture > 0.25:
        planting = "Suitable"
    else:
        planting = "Not suitable"
    insights["optimal_planting_time"] = planting

    # 4️⃣ Crop Stress Indicators
    if wsi > 0.8 or soil_moisture < 0.2:
        stress = "High stress"
    elif 0.5 < wsi <= 0.8:
        stress = "Moderate stress"
    else:
        stress = "Low stress"
    insights["crop_stress_indicator"] = stress

    return pd.Series(insights)


# Apply to DataFrame
df_insights = df.apply(get_agri_insights, axis=1)

# Merge with original data
df_final = pd.concat([df, df_insights], axis=1)

print(df_final.head())

# Replace 'your_data.csv' with your actual file
df2 = pd.read_csv("agriculture_daily_forecast.csv")

print(df2.head())  # check first few rows

def get_agri_insights(row):
    temp = row["temperature_2m"]
    humidity = row["relative_humidity_2m"]
    precip = row["precipitation"]
    wind_speed = row["wind_speed_10m"]
    soil_temp = row["soil_temperature_0cm"]
    soil_moisture = row["soil_moisture_0_1cm"]
    wsi = row["water_stress_index"]
    gdd = row["growing_degree_days"]

    insights = {}

    # 1️⃣ Crop Water Requirement (simple heuristic)
    cwr = (0.0023 * (temp + 17.8) * (temp - 5) * (1 + wind_speed/100))
    insights["crop_water_requirement_mm"] = round(max(cwr, 0), 2)

    # 2️⃣ Pest & Disease Risk
    if temp > 28 and humidity > 75:
        risk = "High risk"
    elif humidity > 65 and 22 < temp < 28:
        risk = "Moderate risk"
    else:
        risk = "Low risk"
    insights["pest_disease_risk"] = risk

    # 3️⃣ Optimal Planting Times
    if 20 <= soil_temp <= 30 and soil_moisture > 0.25:
        planting = "Suitable"
    else:
        planting = "Not suitable"
    insights["optimal_planting_time"] = planting

    # 4️⃣ Crop Stress Indicators
    if wsi > 0.8 or soil_moisture < 0.2:
        stress = "High stress"
    elif 0.5 < wsi <= 0.8:
        stress = "Moderate stress"
    else:
        stress = "Low stress"
    insights["crop_stress_indicator"] = stress

    return pd.Series(insights)


# Apply to DataFrame
df_insights = df.apply(get_agri_insights, axis=1)

# Merge with original data
df_final = pd.concat([df, df_insights], axis=1)

print(df_final.head())